backend:
  name: git-gateway
  branch: master

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "coupons"
    label: "Cupons"
    files:
      - label: "Lista de Cupons"
        name: "coupons"
        file: "data/coupons.json"
        fields:
          - label: "Itens"
            name: "items"
            widget: "list"
            fields:
              - { label: "Categoria (Aba)", name: "category", widget: "string" }
              - { label: "Ícone (emoji)", name: "icon", widget: "string", required: false }
              - { label: "Empresa", name: "brand", widget: "string" }
              - { label: "Descrição", name: "description", widget: "string" }
              - { label: "Cupom", name: "code", widget: "string" }
              - { label: "Link (opcional)", name: "url", widget: "string", required: false }

  - name: "products"
    label: "Produtos"
    files:
      - label: "Lista de Produtos"
        name: "products"
        file: "data/products.json"
        fields:
          - label: "Itens"
            name: "items"
            widget: "list"
            fields:
              - { label: "Categoria (Aba)", name: "category", widget: "string" }
              - { label: "Imagem (URL)", name: "image_url", widget: "string", required: false }
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Descrição", name: "description", widget: "string" }
              - { label: "Link", name: "url", widget: "string" }
